# Generated by Django 4.0.3 on 2025-01-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIBPayment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountstatement',
            table='CIBPayment_accountstatement',
        ),
        migrations.AlterModelTable(
            name='transactioninitiation',
            table='CIBPayment_transactioninitiation',
        ),
        migrations.AlterModelTable(
            name='transactionstatus',
            table='CIBPayment_transactionstatus',
        ),
    ]
