# Generated by Django 4.0.3 on 2025-01-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIBPayment', '0003_balance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='balance',
            table='CIBPayment_balance',
        ),
    ]
