# Generated by Django 4.0.3 on 2025-01-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIBPayment', '0004_alter_balance_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
