# Generated by Django 4.0.3 on 2025-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIBPayment', '0005_delete_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='transaction_type',
            field=models.CharField(choices=[('fruitly', 'Fruitly'), ('other', 'Other')], default='fruitly', max_length=10),
        ),
    ]
